[package]
name = "lock-in"
version = "0.1.1"
edition = "2021"
author = "Nico Estrada"
description = "A CLI tool to stay locked in what you're working on."
license = "MIT"
repository = "https://github.com/nicoestrada/locked_in"

[dependencies]
chrono = "0.4"
